# Anan's Sketchbook Chat Box Configuration - Web API版本

# 使用字体的文件名, 需要自己导入
font_file: "font.ttf"

# 文本换行算法，可选值："original"(原始算法), "knuth_plass"(改进的Knuth-Plass算法)
text_wrap_algorithm: "original"

# 将差分表情导入，默认底图base.png
baseimage_mapping:
  "#普通#": "BaseImages\\base.png"
  "#开心#": "BaseImages\\开心.png"
  "#生气#": "BaseImages\\生气.png"
  "#无语#": "BaseImages\\无语.png"
  "#脸红#": "BaseImages\\脸红.png"
  "#病娇#": "BaseImages\\病娇.png"
  "#闭眼#": "BaseImages\\闭眼.png"
  "#难受#": "BaseImages\\难受.png"
  "#害怕#": "BaseImages\\害怕.png"
  "#激动#": "BaseImages\\激动.png"
  "#惊讶#": "BaseImages\\惊讶.png"
  "#哭泣#": "BaseImages\\哭泣.png"

baseimage_file: "BaseImages\\base.png"

# 文本框左上角坐标 (x, y), 同时适用于图片框
text_box_topleft: [119, 450]

# 文本框右下角坐标 (x, y), 同时适用于图片框
image_box_bottomright: [398, 625]  # (119 + 279, 450 + 175)

# 置顶图层的文件名, 需要自己导入
base_overlay_file: "BaseImages\\base_overlay.png"

# 是否启用底图的置顶图层, 用于表现遮挡
use_base_overlay: true

# 日志记录等级, 可选值有 "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
logging_level: "INFO"